### ISSUE TITLE
Fix header/footer inconsistencies

### ISSUE THREAD

**Issue by rzats** [snowplow/snowplowanalytics.com#104]
![image](https://cloud.githubusercontent.com/assets/13783592/25344570/303e81d8-291b-11e7-968a-94ae98bf18d8.png)

- [ ] **_Company > Careers_ should be added to the footer** - the Careers page is currently really easy to miss.
- [ ] _Services > Data Analytics_ and _Services > Data Engineering_ should be added to the header.
- [ ] Sections should be consistently ordered (either _Services_ followed by _Customers_ or _Customers_ followed by _Services_).
- [ ] Subsections should be consistently named (_Products > Snowplow React^BETA_ or _Products > Snowplow React_; _Resources > Discord_ or _Resources > Community_).

**Comment by jorgemgoncalves** [comment]
I've done all the required changes to the navigator and footer. Please review.

**Comment by yalisassoon** [comment]
Thanks @jorgemgoncalves - that looks good but we still don't have a link to our careers section in the footer. That makes it a lot harder for people to find...

**Comment by jorgemgoncalves** [comment]
@yalisassoon actually I added the link in the footer on the written part on the left. 

The issue we came across when we created the footer was due to bootstraps column system and distributing the newsletter subscription plus 5 columns were leaving very little space between items.

If you think this doesn't solve the situation we can try to take a look at it again.

**Comment by yalisassoon** [comment]
That works for the moment - closing!
