### ISSUE TITLE
Replace Simon Rumble quote with another

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#121]
@ggaviani - can you please look through the different quotes we have from meetups and case studies and think of some suitable alternatives please? Then reassign the ticket to me.

Thanks!

**Comment by ggaviani** [comment]
@yalisassoon , yes, I have done that. See below the quotes I have collected! We could use all of them on our website.

"The core of our analytics pipeline is the open-source, event analytics platform Snowplow, which I believe is a game-changer in the data analytics world. The platform leverages the latest (AWS) technologies, is cost effective and has a lively community".
Dejan Petelin, Head of Data Science, Gousto
https://techbrunch.gousto.co.uk/2016/04/27/snowplow-intro/

"Snowplow plays an integral part of our data infrastructure, allowing us to collect very granular data on our customers’ interactions. Besides collecting interaction events from our website, mobile apps and emails, we also use Snowplow as a unified log collecting backend events, which completes a single customer view".
Dejan Petelin, Head of Data Science, Gousto
https://techbrunch.gousto.co.uk/2017/02/09/snowplow-meetup/

"Snowplow Analytics runs entirely in your AWS account. This means you control the whole process, from tracking to storage and have full ownership of the raw data. Data ownership is important because it gives you the ability to enrich and integrate with other sources, potentially increasing the value of the data".
João Correia, Senior Analytics Strategist, YouCaring
https://joaocorreia.io/blog/how-to-supercharge-your-growth-with-snowplow-analytics.html

“Having a web analytics platform with summarized data, like Google Analytics, can provide immense value to many organizations, but the future of web analytics is not summarized data, it's large amounts of structured and highly granular enriched data that can provide even more value in the hands of the right team. Snowplow gives me complete ownership of my clickstream data with total flexibility at an affordable cost”.
João Correia, Senior Analytics Strategist, YouCaring
_Source: users / testimonials page on previous Snowplow website.
Note: I have updated Joao’s role, previously Analytics Strategist at Blast Analytics and Marketing at the time he gave this quote._

“Snowplow provides rich, granular data, that enabled us to build a sophisticated audience intelligence and double the efficiency of trailer advertising campaigns for our clients compared to the industry averages”
Dominik Raute, Co-Founder & CTO, JustWatch

“Having access to the event-level data with Snowplow enables us to not only finely
segment users, but also provide users with highly personalized adverts and experience”
Sixtine Vervial, Data Analyst, JustWatch

"The Snowplow data set has become part of our core strategic offering."
Stewart Duncan, Director of Data Science, Simply Business

“Pretty much everyone at Simply Business uses Snowplow, especially the product
development team. They use that continuously, every day, to analyse the user
journey and question set. Even the core metrics we use for our management reporting
at board level are aggregations from the Snowplow data”
Stewart Duncan, Director of Data Science, Simply Business

“Snowplow is really powerful when you start to hit that growth curve and going upwards: when you see the signs of accelerating growth and you need to start collecting as much event data as possible”
Thomas in’t Veld, Lead Data Scientist, Peak
https://snowplowanalytics.com/blog/2017/03/03/how-peak-uses-snowplow-to-drive-product-development-and-neuroscience/

“We are happy with how quickly, effectively and on budget we got our data pipeline solution up and running. We turn to Snowplow not only for expertise on the core product but also leverage them as an outsourced member of our data-analytics team. Snowplow is a big success for us”.
Dani Waxman, Product Manager, Viewbix
https://snowplowanalytics.com/blog/2016/10/17/how-viewbix-uses-snowplow-to-enable-their-customers-to-make-data-driven-decisions/

“We're avid fans of Snowplow Analytics. It allows us to track large-scale experiments whilst enabling us to answer business questions no one else can answer. We love it and our clients reap the rewards”
Robert Kingston, Director, MintMetrics.IO
_Source: users / testimonials page on previous Snowplow website_

“Snowplow is the next generation web analytics for data driven organisations. At Hipper.com we could no longer extract incremental value from canned aggregated reports that you get from run of the mill SaaS web analytics solutions. Snowplow enables us to take ownership of granular visitor behavioural data, which yields significant actionable insights and optimisation possibilities around the visitor’s journey”.
Martin Johansson, Managing Director, Hipper.com
_Source: users / testimonials page on previous Snowplow website_

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - can we please update the quote with the one from Martin Johansson, Managing Director, Hipper.com

> Snowplow is the next generation web analytics for data driven organisations. At Hipper.com we could no longer extract incremental value from canned aggregated reports that you get from run of the mill SaaS web analytics solutions. Snowplow enables us to take ownership of granular visitor behavioural data, which yields significant actionable insights and optimisation possibilities around the visitor’s journey

You can find his photo [here](https://www.linkedin.com/in/martin-johansson-a8b91417/?ppe=1)

Thanks!

**Comment by jorgemgoncalves** [comment]
@yalisassoon if we replace Simon's testimonial with Martin's we'll continue to have only 2 testimonials.

You can choose on another testimonial so that we have several scattered on the site?

**Comment by yalisassoon** [comment]
Great! Let's add a few more then 😄 

Let's add the one from Rob Kingson. His photo can be found [here](https://www.linkedin.com/in/robertkingston/).

> “We're avid fans of Snowplow Analytics. It allows us to track large-scale experiments whilst enabling us to answer business questions no one else can answer. We love it and our clients reap the rewards”
Robert Kingston, Director, MintMetrics.IO

Let's add the one from Thomas @ Peak (we have a photo of him already on our blog and one from Dejan @ Gousto:

> "Snowplow plays an integral part of our data infrastructure, allowing us to collect very granular data on our customers’ interactions. Besides collecting interaction events from our website, mobile apps and emails, we also use Snowplow as a unified log collecting backend events, which completes a single customer view".
Dejan Petelin, Head of Data Science, Gousto

You can find a photo of him [here](https://www.linkedin.com/in/dejanpetelin/)

Thanks!

**Comment by jorgemgoncalves** [comment]
@yalisassoon I've added Rob's and Dejan testimonial to the website's Data folder but Dejan LinkedIn photo isn't good enough to publish online and so I've only placed Rob's testimonial in one of the pages.
