### ISSUE TITLE
Correct #anchor links on Blog posts

### ISSUE THREAD

**Issue by dangregorio** [snowplow/snowplowanalytics.com#212]
@yalisassoon The #anchor links on the posts are being used in a wrong way. Menu/list not working. (ie: https://snowplowanalytics.com/blog/2017/07/07/kinesis-s3-0.5.0-released/).

Wrong: Fix silent suppresion of failures](/blog/2017/07/07/kinesis-s3-0.5.0-released#fix)
Correct: Fix silent suppresion of failures](#fix)

**Comment by alexanderdean** [comment]
I remember the reason was so that the links still worked from the blog summary page (maybe this has changed and is no longer required)

**Comment by BenFradet** [comment]
the links aren't even rendered in the blog summary page now, so I guess we could skip it, no?

**Comment by BenFradet** [comment]
Just tested locally and the `[Fix silent suppresion of failures](#fix)` do not work

**Comment by BenFradet** [comment]
I think those links have been broken recently, they don't work on the live website for me anymore.

**Comment by yalisassoon** [comment]
So the requirement here is just that the links start to work. I'm not sure why they don't work now but if we can get this fixed that'd be good because it's definitely a bug.

A theory from @jorgemgoncalves - is this related to an old issue (now fixed) where the anchor links took you to the wrong part of the blog. (Because of an offset in the CSS introduced by the header that needed to be accounted for.)

**Comment by yalisassoon** [comment]
I think the links now work (previously they just broke) but they're all slightly offset becuase the header is effectively covering up the anchor.

This isn't a big deal so if we can't fix it let's not spend too much time on it but if it is a quikc fix then great.

**Comment by yalisassoon** [comment]
Love the way it works now!
