### ISSUE TITLE
Italicised (?) second W in logo is super-cheesy

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplowanalytics.com#23]
Only 3% of the largest 100 brands in the US use an alternative formatting for a single letter in their logo (Max Factor, Hyatt, Dell):

https://www.rankingthebrands.com/The-Brand-Rankings.aspx?rankingID=179

I would argue that all three of these logos have made the alternative formatting of a single letter a **highly integrated** part of the brand. By comparison the italicised second W in Snowplow doesn't tell me anything - it just seems to be "because we can".

**Comment by dangregorio** [comment]
If you remember, this logo is the result of the first tests we did for the brand when creating the new graphic language that was essential to develop the website.
We agreed to give priority to the website and leave the brand details for after.

Here you can see the evolution and the multiple versions we did at that time:
https://drive.google.com/open?id=0BwwSh8n94UreTmJnUHppeU1lSW8

Our feedback:
You can easily get it wrong when comparing to the world top brands. Well known brands always have the advantage of being known. If you want we can address this topic on a next Skype. 

1. The first and obvious purpose of that W is to differentiate the brand. Is it strange? Makes you think? Makes you wonder? Great! You will remember it! Being memorable is one of the biggest challenges for today brands.

Until now we focused the on the graphic element of the hexagon (simplification of the snow flake) to create the brand universe. The W could also be an alternative.

2. The concept behind the Snowplow logo is the data pipeline.  An element changes from the beginning to the end of the process - collect data, work on that data, develop an updated version.
The W at the end represents that change, that dynamic. The movement that something is changing, something new comes next.

3. Instead of using an image of a real Snowplow, which is the basic approach, we've tried to reproduce its characteristics and associate them with the company values; strength, endurance, ploughing, leading the way, etc, represented by the specially customised bold font.

Of course, this is our view of the brand, based on our large experience and knowledge of today's trends. We know that there will always be other opinions and comments are welcome. We just need to receive all those inputs (the earlier, the better) to work on a more consensual version.

**Comment by alexanderdean** [comment]
Thanks @dangregorio , look forward to discussing!

**Comment by yalisassoon** [comment]
Discussion has happened and logo is being developed - closing this issue
