### ISSUE TITLE
Partners section: enable users to filter by region

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#357]
Something like https://www.optimizely.com/partners/solutions/

**Comment by jorgemgoncalves** [comment]
Also add Igloo Analytics to the Implementation Partner section on the main page.

**Comment by jorgemgoncalves** [comment]
Hey guys! @yalisassoon @Mandelliant we've already PR all the changes in the Partners page to QA. 
Unfortunately some images are having a problem which I can't identify and aren't being loaded, which is rather strange because I've checked all the paths and event the folders and they are correct...

Do you have any idea?

**Comment by yalisassoon** [comment]
Hi @jorgemgoncalves - not sure what you mean here - let's discuss today...

**Comment by jorgemgoncalves** [comment]
Hi @yalisassoon & @Mandelliant , already solved the image path issues.

Created PR #554 that deploys the changes to next.

**Comment by yalisassoon** [comment]
Part of the PR that should be merged today
