### ISSUE TITLE
Categories links on blogs don't work for categories with more than one word

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplowanalytics.com#49]
When any of the links in the circle are clicked:

![image](https://cloud.githubusercontent.com/assets/201147/24800154/9b2b84fe-1ba7-11e7-8cf5-c6e780352b2d.png)

A page returns with the following error:

```
Not Found

`/blog/documentation/' not found.
WEBrick/1.3.1 (Ruby/2.0.0/2015-12-16) at localhost:4001
```

**Comment by petermonte** [comment]
Links like `resources/blog/data-modeling/`are resulting in `resources/blog/data%20modeling/` I really don't understand why the `-` character is being interpreted with a whitespace.

**Comment by yalisassoon** [comment]
Hi @petermonte - looking at our old code it looks like this was an issue we came across and wrote some pretty ugly code to handle: https://github.com/snowplow/snowplow.github.com/blob/master/_includes/JB/categories_list#L27.

**Comment by petermonte** [comment]
@yalisassoon Yes I know. I copied all the JB folder knowing that it was required for that purpose. I also realise that the links needed to be changed since we now have blog under Resources. 

What I don't understand is why it is not working. Could there be any configuration we are missing? Those files are like they were on previous website.

**Comment by yalisassoon** [comment]
I don't know - might an alternative be to rename the pages so that they match the URLs that are auto-generated? E.g. `resources/blog/data%20modeling/` rather than `resources/blog/data-modeling/`.

Not sure if this is bad practice from an SEO perspective?

**Comment by jorgemgoncalves** [comment]
I believe that this is already working?

**Comment by yalisassoon** [comment]
Sadly not - the links to categories which are one word categories work, but any two or more word categories dont' work e.g. 'data modeling', 'inside the plow', 'user stories'.

Please can we either get this fixed tomorrow or remove the categories section and create a ticket to add it back pending resolution in a future release?

Thanks

**Comment by jbeemster** [comment]
The links need to be hyphenated rather than percent escaped:

* Current: https://next.snowplowanalytics.com/resources/blog/inside%20the%20plow/
* Working: https://next.snowplowanalytics.com/resources/blog/inside-the-plow/

**Comment by petermonte** [comment]
@yalisassoon 

this issue is fixed. Please review commits [8c60fe4](https://github.com/snowplow/snowplowanalytics.com/commit/8c60fe4334e91845f04df4de7e330a754a451a65), [27f549c](https://github.com/snowplow/snowplowanalytics.com/commit/27f549c9aa6e82271f8da8c9726478111cdbb4fd) and [05bb211](https://github.com/snowplow/snowplowanalytics.com/commit/05bb21190b038e9d052fb0d0273801db3206b540)

**Comment by yalisassoon** [comment]
Awesome! Thanks so much @petermonte. Closing.
