### ISSUE TITLE
Come up with a solution for showing blog posts that are old blog posts

### ISSUE THREAD

**Issue by ggaviani** [snowplow/snowplowanalytics.com#77]
The list of blog posts is not complete: both most recent and older ones are missing.
- The latest blog post showing is dated March 3rd, but we published several others since.
- the oldest one appearing is dated January 9th (2017)

**Comment by yalisassoon** [comment]
@ggaviani I've added the recent content.

@jorgemgoncalves @petermonte the current solution shows a fixed number of blog posts, with no option to view posts that are older. The current site has an 'all posts' page [here](http://snowplowanalytics.com/blog/archive/) that is linkable via a button on the bottom of the blog roll. 

The new website does have a page with all the posts: https://next.snowplowanalytics.com/resources/blog/archive/. However this is not linked to, I don't believe...

**Comment by petermonte** [comment]
@yalisassoon 

- So it seems that we're missing the button to point to the [archive](https://next.snowplowanalytics.com/resources/blog/archive/). Do you want this button under the the [blog most recent posts](https://next.snowplowanalytics.com/resources/blog/)?

- As you may understand the building of the new website never got daily updated with what is updated on the new site. So this process needs to be addressed before launch with the copy of all posts from the old site to the new. It will require a find&replace to configure the new vars for layout.

**Comment by yalisassoon** [comment]
Hi @petermonte - I moved over the blog posts that had been published since the development started from the old website to the new website over the weekend. I copied over each post markdown file, and the additional assets (mostly images) used in them.

Are there additional variables that need to be updated for those posts that I migrated? I think they work fine but may have missed something...
